[package]
name = "quickdraw-ui"
version.workspace = true
edition.workspace = true

[dependencies]
quickdraw-core = { path = "../quickdraw-core" }
quickdraw-defi = { path = "../quickdraw-defi" }
eframe         = { workspace = true }
egui           = { workspace = true }
egui-phosphor  = { workspace = true }
egui_plot      = { workspace = true }
tokio          = { workspace = true }
serde          = { workspace = true }
anyhow         = { workspace = true }
thiserror      = { workspace = true }
tracing        = { workspace = true }
solana-sdk     = { workspace = true }
open           = { workspace = true }
